from __future__ import annotations


LOCAL_RETRIEVAL_SEARCH_CONTRACT = (
    'Any',
    'RRF_K',
    'RetrievalBackend',
    'RetrievalCitation',
    'RetrievalHit',
    'RetrievalProfile',
    'RetrievalQueryPlan',
    'RetrievalSearchResponse',
    '_build_query_plan',
    '_category_boost',
    '_corrective_retry_query',
    '_document_diversified_hits',
    '_enrich_hit_metadata',
    '_intent_alignment_boost',
    '_normalize_category_filter',
    '_normalize_hit_labels',
    '_normalize_text',
    '_normalize_visibility_filter',
    '_query_terms',
    '_section_alignment_boost',
    '_should_recommend_citation_first',
    '_source_weight',
    '_subquery_coverage_map',
    '_uncovered_subqueries',
    'dict_row',
    'monotonic',
    'psycopg',
    'record_counter',
    'record_histogram',
    'set_span_attributes',
    'start_span',
)
