"""initial schema foundation

Revision ID: 434bee84d7d9
Revises: 
Create Date: 2026-03-23 02:24:13.045063
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '434bee84d7d9'
down_revision = None
branch_labels = None
depends_on = None

SCHEMAS = (
    'identity',
    'school',
    'academic',
    'finance',
    'calendar',
    'documents',
    'conversation',
    'audit',
)


def upgrade() -> None:
    for schema_name in SCHEMAS:
        op.execute(sa.text(f'CREATE SCHEMA IF NOT EXISTS "{schema_name}"'))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_sets',
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('visibility', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_sets')),
    sa.UniqueConstraint('slug', name=op.f('uq_document_sets_slug')),
    schema='documents'
    )
    op.create_table('roles',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_roles')),
    schema='identity'
    )
    op.create_table('telegram_accounts',
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_accounts')),
    sa.UniqueConstraint('telegram_chat_id', name=op.f('uq_telegram_accounts_telegram_chat_id')),
    sa.UniqueConstraint('telegram_user_id', name=op.f('uq_telegram_accounts_telegram_user_id')),
    schema='identity'
    )
    op.create_table('school_units',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_school_units')),
    sa.UniqueConstraint('code', name=op.f('uq_school_units_code')),
    schema='school'
    )
    op.create_table('subjects',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=False),
    sa.Column('weekly_hours', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects')),
    sa.UniqueConstraint('code', name=op.f('uq_subjects_code')),
    schema='school'
    )
    op.create_table('documents',
    sa.Column('document_set_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('audience', sa.String(length=60), nullable=False),
    sa.Column('visibility', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_set_id'], ['documents.document_sets.id'], name=op.f('fk_documents_document_set_id_document_sets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    schema='documents'
    )
    op.create_table('users',
    sa.Column('role_code', sa.String(length=50), nullable=False),
    sa.Column('external_code', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_code'], ['identity.roles.code'], name=op.f('fk_users_role_code_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('external_code', name=op.f('uq_users_external_code')),
    schema='identity'
    )
    op.create_table('access_decisions',
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('resource_type', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['identity.users.id'], name=op.f('fk_access_decisions_actor_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access_decisions')),
    schema='audit'
    )
    op.create_table('audit_events',
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=120), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['identity.users.id'], name=op.f('fk_audit_events_actor_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events')),
    schema='audit'
    )
    op.create_table('conversations',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('external_thread_id', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], name=op.f('fk_conversations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations')),
    schema='conversation'
    )
    op.create_table('document_versions',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_label', sa.String(length=20), nullable=False),
    sa.Column('storage_path', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.documents.id'], name=op.f('fk_document_versions_document_id_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_versions')),
    sa.UniqueConstraint('document_id', 'version_label', name=op.f('uq_document_versions_document_id')),
    schema='documents'
    )
    op.create_table('user_telegram_links',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('telegram_account_id', sa.UUID(), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['telegram_account_id'], ['identity.telegram_accounts.id'], name=op.f('fk_user_telegram_links_telegram_account_id_telegram_accounts')),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], name=op.f('fk_user_telegram_links_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_telegram_links')),
    sa.UniqueConstraint('telegram_account_id', name=op.f('uq_user_telegram_links_telegram_account_id')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_telegram_links_user_id')),
    schema='identity'
    )
    op.create_table('guardians',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('relationship_label', sa.String(length=40), nullable=False),
    sa.Column('cpf_masked', sa.String(length=20), nullable=False),
    sa.Column('primary_contact', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], name=op.f('fk_guardians_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guardians')),
    schema='school'
    )
    op.create_table('students',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('school_unit_id', sa.UUID(), nullable=False),
    sa.Column('enrollment_code', sa.String(length=40), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('current_grade_level', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_unit_id'], ['school.school_units.id'], name=op.f('fk_students_school_unit_id_school_units')),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], name=op.f('fk_students_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students')),
    sa.UniqueConstraint('enrollment_code', name=op.f('uq_students_enrollment_code')),
    schema='school'
    )
    op.create_table('teachers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('school_unit_id', sa.UUID(), nullable=False),
    sa.Column('employee_code', sa.String(length=40), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_unit_id'], ['school.school_units.id'], name=op.f('fk_teachers_school_unit_id_school_units')),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], name=op.f('fk_teachers_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teachers')),
    sa.UniqueConstraint('employee_code', name=op.f('uq_teachers_employee_code')),
    schema='school'
    )
    op.create_table('handoffs',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('queue_name', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.conversations.id'], name=op.f('fk_handoffs_conversation_id_conversations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_handoffs')),
    schema='conversation'
    )
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.conversations.id'], name=op.f('fk_messages_conversation_id_conversations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    schema='conversation'
    )
    op.create_table('tool_calls',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.conversations.id'], name=op.f('fk_tool_calls_conversation_id_conversations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_calls')),
    schema='conversation'
    )
    op.create_table('document_chunks',
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('contextual_summary', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['documents.document_versions.id'], name=op.f('fk_document_chunks_document_version_id_document_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks')),
    sa.UniqueConstraint('document_version_id', 'chunk_index', name=op.f('uq_document_chunks_document_version_id')),
    schema='documents'
    )
    op.create_table('contracts',
    sa.Column('school_unit_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('guardian_id', sa.UUID(), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('contract_code', sa.String(length=40), nullable=False),
    sa.Column('monthly_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['school.guardians.id'], name=op.f('fk_contracts_guardian_id_guardians')),
    sa.ForeignKeyConstraint(['school_unit_id'], ['school.school_units.id'], name=op.f('fk_contracts_school_unit_id_school_units')),
    sa.ForeignKeyConstraint(['student_id'], ['school.students.id'], name=op.f('fk_contracts_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contracts')),
    sa.UniqueConstraint('contract_code', name=op.f('uq_contracts_contract_code')),
    schema='finance'
    )
    op.create_table('classes',
    sa.Column('school_unit_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('grade_level', sa.Integer(), nullable=False),
    sa.Column('shift', sa.String(length=30), nullable=False),
    sa.Column('homeroom_teacher_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['homeroom_teacher_id'], ['school.teachers.id'], name=op.f('fk_classes_homeroom_teacher_id_teachers')),
    sa.ForeignKeyConstraint(['school_unit_id'], ['school.school_units.id'], name=op.f('fk_classes_school_unit_id_school_units')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classes')),
    sa.UniqueConstraint('school_unit_id', 'code', name=op.f('uq_classes_school_unit_id')),
    schema='school'
    )
    op.create_table('guardian_student_links',
    sa.Column('guardian_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('relationship_label', sa.String(length=40), nullable=False),
    sa.Column('can_view_finance', sa.Boolean(), nullable=False),
    sa.Column('can_view_academic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['school.guardians.id'], name=op.f('fk_guardian_student_links_guardian_id_guardians')),
    sa.ForeignKeyConstraint(['student_id'], ['school.students.id'], name=op.f('fk_guardian_student_links_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guardian_student_links')),
    sa.UniqueConstraint('guardian_id', 'student_id', name=op.f('uq_guardian_student_links_guardian_id')),
    schema='school'
    )
    op.create_table('teacher_assignments',
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['school.classes.id'], name=op.f('fk_teacher_assignments_class_id_classes')),
    sa.ForeignKeyConstraint(['subject_id'], ['school.subjects.id'], name=op.f('fk_teacher_assignments_subject_id_subjects')),
    sa.ForeignKeyConstraint(['teacher_id'], ['school.teachers.id'], name=op.f('fk_teacher_assignments_teacher_id_teachers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher_assignments')),
    sa.UniqueConstraint('teacher_id', 'class_id', 'subject_id', 'academic_year', name=op.f('uq_teacher_assignments_teacher_id')),
    schema='academic'
    )
    op.create_table('calendar_events',
    sa.Column('school_unit_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=True),
    sa.Column('audience', sa.String(length=40), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('visibility', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['school.classes.id'], name=op.f('fk_calendar_events_class_id_classes')),
    sa.ForeignKeyConstraint(['school_unit_id'], ['school.school_units.id'], name=op.f('fk_calendar_events_school_unit_id_school_units')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_events')),
    schema='calendar'
    )
    op.create_table('retrieval_labels',
    sa.Column('document_chunk_id', sa.UUID(), nullable=False),
    sa.Column('label_type', sa.String(length=40), nullable=False),
    sa.Column('label_value', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_chunk_id'], ['documents.document_chunks.id'], name=op.f('fk_retrieval_labels_document_chunk_id_document_chunks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retrieval_labels')),
    schema='documents'
    )
    op.create_table('invoices',
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('reference_month', sa.String(length=7), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['finance.contracts.id'], name=op.f('fk_invoices_contract_id_contracts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices')),
    sa.UniqueConstraint('contract_id', 'reference_month', name=op.f('uq_invoices_contract_id')),
    schema='finance'
    )
    op.create_table('enrollments',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('enrollment_status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['school.classes.id'], name=op.f('fk_enrollments_class_id_classes')),
    sa.ForeignKeyConstraint(['student_id'], ['school.students.id'], name=op.f('fk_enrollments_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollments')),
    sa.UniqueConstraint('student_id', 'class_id', 'academic_year', name=op.f('uq_enrollments_student_id')),
    schema='school'
    )
    op.create_table('attendance_records',
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('minutes_absent', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['school.enrollments.id'], name=op.f('fk_attendance_records_enrollment_id_enrollments')),
    sa.ForeignKeyConstraint(['subject_id'], ['school.subjects.id'], name=op.f('fk_attendance_records_subject_id_subjects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_records')),
    schema='academic'
    )
    op.create_table('grade_items',
    sa.Column('teacher_assignment_id', sa.UUID(), nullable=False),
    sa.Column('term_code', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_assignment_id'], ['academic.teacher_assignments.id'], name=op.f('fk_grade_items_teacher_assignment_id_teacher_assignments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grade_items')),
    schema='academic'
    )
    op.create_table('payments',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('paid_at', sa.Date(), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['finance.invoices.id'], name=op.f('fk_payments_invoice_id_invoices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    schema='finance'
    )
    op.create_table('grades',
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('grade_item_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('feedback', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['school.enrollments.id'], name=op.f('fk_grades_enrollment_id_enrollments')),
    sa.ForeignKeyConstraint(['grade_item_id'], ['academic.grade_items.id'], name=op.f('fk_grades_grade_item_id_grade_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grades')),
    sa.UniqueConstraint('enrollment_id', 'grade_item_id', name=op.f('uq_grades_enrollment_id')),
    schema='academic'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grades', schema='academic')
    op.drop_table('payments', schema='finance')
    op.drop_table('grade_items', schema='academic')
    op.drop_table('attendance_records', schema='academic')
    op.drop_table('enrollments', schema='school')
    op.drop_table('invoices', schema='finance')
    op.drop_table('retrieval_labels', schema='documents')
    op.drop_table('calendar_events', schema='calendar')
    op.drop_table('teacher_assignments', schema='academic')
    op.drop_table('guardian_student_links', schema='school')
    op.drop_table('classes', schema='school')
    op.drop_table('contracts', schema='finance')
    op.drop_table('document_chunks', schema='documents')
    op.drop_table('tool_calls', schema='conversation')
    op.drop_table('messages', schema='conversation')
    op.drop_table('handoffs', schema='conversation')
    op.drop_table('teachers', schema='school')
    op.drop_table('students', schema='school')
    op.drop_table('guardians', schema='school')
    op.drop_table('user_telegram_links', schema='identity')
    op.drop_table('document_versions', schema='documents')
    op.drop_table('conversations', schema='conversation')
    op.drop_table('audit_events', schema='audit')
    op.drop_table('access_decisions', schema='audit')
    op.drop_table('users', schema='identity')
    op.drop_table('documents', schema='documents')
    op.drop_table('subjects', schema='school')
    op.drop_table('school_units', schema='school')
    op.drop_table('telegram_accounts', schema='identity')
    op.drop_table('roles', schema='identity')
    op.drop_table('document_sets', schema='documents')
    for schema_name in reversed(SCHEMAS):
        op.execute(sa.text(f'DROP SCHEMA IF EXISTS "{schema_name}" CASCADE'))
    # ### end Alembic commands ###
