from __future__ import annotations


GRAPH_CLASSIFICATION_CONTRACT = (
    'ACADEMIC_TERMS',
    'AccessTier',
    'FINANCE_TERMS',
    'GRAPH_RAG_TERMS',
    'GraphRuntimeConfig',
    'INSTITUTION_TERMS',
    'IntentClassification',
    'OrchestrationMode',
    'OrchestrationState',
    'PUBLIC_CALENDAR_TERMS',
    'PUBLIC_SERVICE_TERMS',
    'QueryDomain',
    '_append_path',
    '_can_read_restricted_documents',
    '_contains_any',
    '_is_admin_finance_combined_query',
    '_is_authenticated_access_scope_query',
    '_is_authenticated_actor_identity_query',
    '_is_authenticated_admin_query',
    '_is_authenticated_finance_attribute_query',
    '_is_authenticated_linked_students_query',
    '_is_authenticated_personal_finance_query',
    '_is_authenticated_student_assessment_query',
    '_is_authenticated_student_registry_query',
    '_is_cross_document_public_query',
    '_is_known_public_doc_bundle_query',
    '_is_public_attribute_followup_query',
    '_is_public_calendar_event_query',
    '_is_public_document_submission_query',
    '_is_public_feature_query',
    '_is_public_navigation_query',
    '_is_public_policy_query',
    '_is_public_pricing_query',
    '_is_public_school_profile_request',
    '_is_public_staff_directory_query',
    '_is_public_timeline_query',
    '_is_public_utility_query',
    '_is_restricted_document_query',
    '_is_structured_support_workflow_request',
    '_is_teacher_self_service_request',
    '_normalize_text',
    '_wants_human_support',
)
