from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class LlamaIndexPublicIntentRule:
    intent_id: str
    priority: int
    conversation_act: str
    answer_mode: str
    any_of: tuple[str, ...] = ()
    all_of: tuple[str, ...] = ()
    none_of: tuple[str, ...] = ()
    required_tools: tuple[str, ...] = ()
    secondary_acts: tuple[str, ...] = ()
    requested_attribute: str | None = None
    requested_channel: str | None = None
    focus_hint: str | None = None
    unpublished_key: str | None = None
    use_conversation_context: bool = True


LLAMAINDEX_PUBLIC_INTENT_RULES: tuple[LlamaIndexPublicIntentRule, ...] = (
    LlamaIndexPublicIntentRule(
        intent_id='contact_bundle',
        priority=101,
        conversation_act='contacts',
        answer_mode='profile',
        any_of=('telefone principal', 'melhor canal', 'secretaria hoje', 'endereco completo'),
        focus_hint='endereco completo, telefone principal e melhor canal para a secretaria hoje',
        requested_channel='secretaria',
    ),
    LlamaIndexPublicIntentRule(
        intent_id='service_routing_matrix',
        priority=100,
        conversation_act='service_routing',
        answer_mode='profile',
        any_of=(
            'com quem eu falo sobre',
            'quem responde por',
            'qual a diferenca entre falar com',
            'qual a diferença entre falar com',
            'diferenca entre secretaria',
            'diferença entre secretaria',
        ),
        focus_hint='roteamento publico entre admissions, financeiro, orientacao educacional, direcao e secretaria',
    ),
    LlamaIndexPublicIntentRule(
        intent_id='service_credentials_bundle',
        priority=99,
        conversation_act='service_credentials_bundle',
        answer_mode='profile',
        any_of=(
            'credenciais',
            'credencial',
            'login',
            'senha',
            'secretaria portal credenciais',
            'portal credenciais',
            'portal aplicativo senha',
        ),
        focus_hint='secretaria, portal institucional, credenciais e envio de documentos',
        requested_attribute='service_credentials_bundle',
    ),
    LlamaIndexPublicIntentRule(
        intent_id='public_policy',
        priority=98,
        conversation_act='policy',
        answer_mode='profile',
        any_of=(
            'politica de avaliacao',
            'politica de avaliação',
            'recuperacao e promocao',
            'recuperação e promoção',
            'projeto de vida',
            'frequencia minima',
            'frequência mínima',
            '75%',
        ),
        focus_hint='politica publica de avaliacao, recuperacao, promocao, projeto de vida e frequencia',
        requested_attribute='academic_policy',
    ),
    LlamaIndexPublicIntentRule(
        intent_id='policy_compare',
        priority=97,
        conversation_act='policy_compare',
        answer_mode='profile',
        any_of=('compare', 'comparar', 'comparacao', 'comparação'),
        all_of=('regulamentos', 'avaliacao'),
        focus_hint='comparacao entre regulamentos gerais, frequencia, aprovacao e recuperacao',
        requested_attribute='academic_policy',
    ),
    LlamaIndexPublicIntentRule(
        intent_id='auth_guidance',
        priority=96,
        conversation_act='auth_guidance',
        answer_mode='profile',
        any_of=('como eu vinculo', 'como vinculo minha conta', 'link_', 'telegram a minha conta'),
        focus_hint='vinculacao do Telegram ao portal autenticado e codigo link_',
    ),
    LlamaIndexPublicIntentRule(
        intent_id='document_submission',
        priority=95,
        conversation_act='document_submission',
        answer_mode='profile',
        any_of=(
            'documentos sao exigidos',
            'quais documentos preciso para matricula',
            'quais documentos preciso para matrícula',
            'documentos para matricula',
            'documentos para matrícula',
            'envio de documentos',
            'atualizacoes cadastrais',
            'declarações',
            'declaracoes',
        ),
        focus_hint='documentos de matricula, secretaria, portal, email da secretaria e prazos',
    ),
    LlamaIndexPublicIntentRule(
        intent_id='timeline_combined',
        priority=94,
        conversation_act='timeline',
        answer_mode='profile',
        any_of=(
            'abre a matricula de 2026',
            'abre a matrícula de 2026',
            'quando comecam as aulas',
            'quando começam as aulas',
            'quando iniciam as aulas',
            'quando inicia o ano letivo',
        ),
        focus_hint='abertura da matricula 2026 e inicio das aulas 2026',
    ),
    LlamaIndexPublicIntentRule(
        intent_id='timeline_lifecycle',
        priority=93,
        conversation_act='timeline',
        answer_mode='profile',
        any_of=(
            'antes da confirmacao da vaga',
            'antes da confirmação da vaga',
            'depois do inicio das aulas',
            'depois do início das aulas',
            'viagem sem atrapalhar a vida escolar',
            'tres fases',
        ),
        focus_hint='marcos publicos entre admissao, inicio das aulas, rotina academica e fechamento do ano',
        requested_attribute='public_timeline',
    ),
    LlamaIndexPublicIntentRule(
        intent_id='documentary_proposal',
        priority=92,
        conversation_act='highlight',
        answer_mode='documentary',
        any_of=(
            'com base nos documentos',
            'cite as fontes',
            'cite os documentos',
            'mostre as fontes',
            'proposta pedagogica',
            'proposta pedagógica',
        ),
        focus_hint='proposta pedagogica, diferenciais, curriculo, apoio pedagogico e evidencias documentais publicas',
    ),
    LlamaIndexPublicIntentRule(
        intent_id='value_proposition',
        priority=91,
        conversation_act='highlight',
        answer_mode='profile',
        any_of=(
            '30 segundos',
            '30s',
            'familia nova',
            'família nova',
            'se eu fosse uma familia nova',
            'se eu fosse uma família nova',
            'por que deveria',
            'porque deveria',
            'por que escolher',
            'porque escolher',
            'vale a pena',
            'diferenciais',
            'motivos para escolher',
        ),
        none_of=(
            'compare',
            'comparar',
            'comparacao',
            'comparação',
            'sintetize',
            'relacione',
            'calendario',
            'calendário',
            'agenda',
            'manual',
            'regulamentos',
            'portal',
            'credenciais',
            'rematricula',
            'rematrícula',
            'transferencia',
            'transferência',
            'cancelamento',
        ),
        focus_hint='diferenciais do colegio, proposta pedagogica, infraestrutura, acompanhamento pedagogico, biblioteca, esportes e vida escolar',
    ),
    LlamaIndexPublicIntentRule(
        intent_id='value_proposition_school',
        priority=90,
        conversation_act='highlight',
        answer_mode='profile',
        any_of=(
            'meus filhos nessa escola',
            'meus filhos nesse colegio',
            'meus filhos nesse colégio',
        ),
        focus_hint='por que escolher o colegio, proposta pedagogica, estrutura, seguranca, biblioteca, esportes e apoio academico',
    ),
    LlamaIndexPublicIntentRule(
        intent_id='scholarship_policy',
        priority=89,
        conversation_act='pricing',
        answer_mode='profile',
        any_of=('bolsa', 'desconto', '50%', '50 por cento', 'meia bolsa'),
        focus_hint='bolsas, descontos, percentuais, criterios, elegibilidade, edital e documentos exigidos',
        requested_attribute='scholarship_policy',
        requested_channel='admissions',
    ),
    LlamaIndexPublicIntentRule(
        intent_id='scholarship_process_bundle',
        priority=88,
        conversation_act='pricing',
        answer_mode='profile',
        any_of=('bolsas', 'descontos', 'rematricula', 'rematrícula', 'transferencia', 'transferência', 'cancelamento'),
        all_of=('bolsa', 'desconto'),
        focus_hint='bolsas, descontos, rematricula, transferencia e cancelamento em uma resposta publica integrada',
        requested_attribute='scholarship_policy',
        requested_channel='admissions',
    ),
    LlamaIndexPublicIntentRule(
        intent_id='minimum_age',
        priority=87,
        conversation_act='segments',
        answer_mode='unpublished',
        any_of=('idade minima', 'idade mínima', 'idade para estudar', 'idade para matricular'),
        unpublished_key='minimum_age',
        requested_attribute='minimum_age',
        requested_channel='admissions',
    ),
    LlamaIndexPublicIntentRule(
        intent_id='classroom_count',
        priority=86,
        conversation_act='features',
        answer_mode='unpublished',
        any_of=('quantas salas', 'quantidade de salas', 'numero de salas', 'número de salas'),
        unpublished_key='classroom_count',
        requested_attribute='classroom_count',
    ),
    LlamaIndexPublicIntentRule(
        intent_id='student_count',
        priority=85,
        conversation_act='kpi',
        answer_mode='unpublished',
        any_of=('quantos alunos', 'quantidade de alunos', 'numero de alunos', 'número de alunos'),
        unpublished_key='total_students',
        requested_attribute='student_count',
    ),
    LlamaIndexPublicIntentRule(
        intent_id='library_book_count',
        priority=84,
        conversation_act='features',
        answer_mode='unpublished',
        any_of=('quantos livros', 'quantidade de livros', 'numero de livros', 'número de livros'),
        all_of=('biblioteca',),
        unpublished_key='library_book_count',
        requested_attribute='library_collection_size',
    ),
    LlamaIndexPublicIntentRule(
        intent_id='cafeteria_menu',
        priority=83,
        conversation_act='features',
        answer_mode='unpublished',
        any_of=('cardapio', 'cardápio'),
        all_of=('cantina',),
        unpublished_key='cafeteria_menu',
        requested_attribute='cafeteria_menu',
        requested_channel='secretaria',
    ),
    LlamaIndexPublicIntentRule(
        intent_id='leadership_name',
        priority=82,
        conversation_act='leadership',
        answer_mode='profile',
        any_of=('diretor', 'diretora', 'direcao', 'direção', 'lideranca', 'liderança'),
        requested_attribute='leadership',
    ),
    LlamaIndexPublicIntentRule(
        intent_id='shift_offers',
        priority=81,
        conversation_act='schedule',
        answer_mode='profile',
        any_of=(
            'turno',
            'turnos',
            'turma',
            'turmas',
            'matutino',
            'matutina',
            'vespertino',
            'vespertina',
            'noturno',
            'noturna',
            'manha',
            'manhã',
            'horario de aula',
            'horário de aula',
            'horario da aula',
            'horário da aula',
            'que horas comeca a aula',
            'que horas começa a aula',
            'aula de manha',
            'aula de manhã',
            'aula da manha',
            'aula da manhã',
            'turno da manha',
            'turno da manhã',
        ),
        none_of=('intervalo', 'recreio'),
        focus_hint='turnos, segmentos, horarios de aula e oferta por periodo',
        requested_attribute='shift_offers',
    ),
    LlamaIndexPublicIntentRule(
        intent_id='interval_schedule',
        priority=80,
        conversation_act='schedule',
        answer_mode='profile',
        any_of=('intervalo', 'intervalos', 'recreio'),
        focus_hint='horarios de intervalo e recreio por segmento',
        requested_attribute='interval_schedule',
    ),
    LlamaIndexPublicIntentRule(
        intent_id='institutional_facilities',
        priority=79,
        conversation_act='features',
        answer_mode='profile',
        any_of=(
            'biblioteca',
            'cantina',
            'laboratorio',
            'laboratório',
            'quadra',
            'sala de professores',
            'piscina',
            'kart',
            'tenis',
            'tênis',
        ),
        focus_hint='infraestrutura, espacos e atividades oficialmente mencionados',
        requested_attribute='feature_inventory',
    ),
    LlamaIndexPublicIntentRule(
        intent_id='institutional_schedule',
        priority=78,
        conversation_act='operating_hours',
        answer_mode='profile',
        any_of=('horario', 'horário', 'atende', 'funciona'),
        focus_hint='horarios publicos de atendimento, biblioteca e canais oficiais',
        requested_attribute='operating_hours',
    ),
    LlamaIndexPublicIntentRule(
        intent_id='calendar_visibility',
        priority=77,
        conversation_act='calendar_events',
        answer_mode='profile',
        any_of=('eventos do calendario', 'eventos do calendário', 'realmente publicos', 'realmente públicos', 'contexto interno'),
        focus_hint='o que fica publico no calendario e o que depende de autenticacao ou contexto interno',
        requested_attribute='public_calendar_events',
    ),
    LlamaIndexPublicIntentRule(
        intent_id='health_second_call',
        priority=76,
        conversation_act='policy',
        answer_mode='profile',
        any_of=('motivo de saude', 'motivo de saúde', 'perder uma prova', 'segunda chamada', 'atestado'),
        focus_hint='atestado, saude e segunda chamada descritos em documentos publicos',
        requested_attribute='academic_policy',
    ),
)
