from __future__ import annotations


LLAMAINDEX_NATIVE_SUPPORT_CONTRACT = (
    'AccessTier',
    'FunctionAgent',
    'FunctionTool',
    'IntentClassification',
    'KernelPlan',
    'KernelReflection',
    'KernelRunResult',
    'LLAMAINDEX_QDRANT_AVAILABLE',
    'LlamaIndexEarlyPublicAnswer',
    'MessageResponse',
    'MessageResponseCitation',
    'MessageResponseRequest',
    'OrchestrationMode',
    'PublicHybridCitationRetriever',
    'PublicRetrievalQueryEngine',
    'QueryDomain',
    'QueryEngineTool',
    'ResponseMode',
    'RetrievalBackend',
    '_await_with_llamaindex_timeout',
    '_build_llamaindex_chat_history',
    '_build_llamaindex_node_postprocessors',
    '_can_read_private_documents',
    '_canonical_lane_answer_for_message',
    '_extract_response_citations',
    '_llamaindex_llm_supports_function_calls',
    '_looks_like_restricted_doc_query',
    '_maybe_contextual_public_direct_answer',
    '_native_qdrant_vector_index',
    '_resolve_llamaindex_qdrant_collection',
    '_restricted_doc_hit_to_citation',
    'build_direct_answer_evidence_pack',
    'build_retrieval_evidence_pack',
    'get_response_synthesizer',
    'get_retrieval_service',
    'match_public_canonical_lane',
    'monotonic',
    'record_stack_outcome',
    'resolve_retrieval_execution_policy',
    'rt',
)
