from __future__ import annotations

PUBLIC_CANONICAL_LANE_COMPOSERS: dict[str, str] = {
    "public_bundle.teacher_directory_boundary": "compose_public_teacher_directory_boundary",
    "public_bundle.inclusion_accessibility": "compose_public_inclusion_accessibility",
    "public_bundle.integral_study_support": "compose_public_integral_study_support",
    "public_bundle.health_emergency_bundle": "compose_public_health_emergency_bundle",
    "public_bundle.outings_authorizations": "compose_public_outings_authorizations",
    "public_bundle.transport_uniform_bundle": "compose_public_transport_uniform_bundle",
    "public_bundle.governance_protocol": "compose_public_governance_protocol",
    "public_bundle.calendar_week": "compose_public_calendar_week",
    "public_bundle.year_three_phases": "compose_public_year_three_phases",
    "public_bundle.academic_policy_overview": "compose_public_academic_policy_overview",
    "public_bundle.access_scope_compare": "compose_public_access_scope_compare",
    "public_bundle.policy_compare": "compose_public_policy_compare",
    "public_bundle.conduct_frequency_punctuality": "compose_public_conduct_frequency_punctuality",
    "public_bundle.family_new_calendar_assessment_enrollment": "compose_public_family_new_calendar_assessment_enrollment",
    "public_bundle.timeline_lifecycle": "compose_public_timeline_lifecycle_bundle",
    "public_bundle.visibility_boundary": "compose_public_calendar_visibility",
    "public_bundle.permanence_family_support": "compose_public_permanence_and_family_support",
    "public_bundle.process_compare": "compose_public_process_compare",
    "public_bundle.health_second_call": "compose_public_health_second_call",
    "public_bundle.health_authorizations_bridge": "compose_public_health_authorizations_bridge",
    "public_bundle.first_month_risks": "compose_public_first_month_risks",
    "public_bundle.conduct_frequency_recovery": "compose_public_conduct_frequency_recovery_bridge",
    "public_bundle.facilities_study_support": "compose_public_facilities_and_study_support",
    "public_bundle.secretaria_portal_credentials": "compose_public_secretaria_portal_credentials",
    "public_bundle.bolsas_and_processes": "compose_public_bolsas_and_processes",
    "public_bundle.transversal_year": "compose_public_transversal_year_bundle",
}
